# 龍が如く (セガ) のキャラクター名

[meta]
schema_version = "2"
role = "works"
description = "龍が如く: キャラクター名"

[entries]

"春日一番" = "カスガイチバン"  # 春日=かすが (default しゅんじつ)
"錦山" = "ニシキヤマ"        # 錦山彰 (default きんざん)
"錦山彰" = "ニシキヤマアキラ"  # 彰=あきら
"堂島大吾" = "ドウジマダイゴ"  # 大吾=だいご (default だいわれ)
