# SI / 一般単位
# `ci = true` で case-insensitive lookup (大文字小文字を区別しない)

[entries]
"km" = { kana = "キロメートル" }
"cm" = { kana = "センチメートル" }
"mm" = { kana = "ミリメートル" }
"m"  = { kana = "メートル" }
"kg" = { kana = "キログラム" }
"mg" = { kana = "ミリグラム" }
"g"  = { kana = "グラム" }
"t"  = { kana = "トン" }
"mL" = { kana = "ミリリットル", ci = true }
"L"  = { kana = "リットル", ci = true }
"TB" = { kana = "テラバイト" }
"GB" = { kana = "ギガバイト" }
"MB" = { kana = "メガバイト" }
"KB" = { kana = "キロバイト" }
